#97140-ContentTypeOptional
SKF/go-tests-utility pull request #21
Opened 2020-11-20 22:47 UTC by kulbhushan-skf

97140-ContentTypeOptional

2020-11-23 15:04 UTC, kulbhushan-skf commented
@rickardenglund Please find the PR.

2020-11-23 15:04 UTC, rickardenglund requested changes

2020-11-23 15:04 UTC, rickardenglund commented on api/godog/requests.go
> +		req.Header = api.Request.Headers
This one should always be set

2020-11-23 15:04 UTC, rickardenglund commented on api/godog/requests.go
> +		req.Header.Set("Content-Type", "application/json")
And I think that we should remove this completly.

if it is needed it should be specified in the gherkin spec.

2020-11-23 19:46 UTC, kulbhushan-skf commented
@rickardenglund updated comments and tested with users repo.

2020-11-24 07:08 UTC, rickardenglund approved these changes

2020-11-24 15:05 UTC, merged